Finished task2
Bazilchuk2020/csdt2324ki49bazilchukmo01 pull request #2
Opened 2023-10-27 18:07 UTC by Bazilchuk2020

2023-10-27 19:46 UTC, andrii-s-spitzer-lpnu-ua commented
you need get grade for task #1 first. After that you can do task#2

2023-10-27 20:06 UTC, andrii-s-spitzer-lpnu-ua requested changes

2023-10-27 20:06 UTC, andrii-s-spitzer-lpnu-ua commented on ConsoleApp18/ConsoleApp18/bin/Debug/net7.0/ConsoleApp18.dll
Please remove all binary files. Git can not manage binary files.

2023-10-27 21:11 UTC, Bazilchuk2020 commented on ConsoleApp18/ConsoleApp18/bin/Debug/net7.0/ConsoleApp18.dll
I cannot see inary files, can you write name of this files and i remove it

2023-10-28 19:48 UTC, andrii-s-spitzer-lpnu-ua commented
ConsoleApp18/ConsoleApp18/bin/Debug/net7.0/ConsoleApp18.exe
ConsoleApp18/ConsoleApp18/bin/Debug/net7.0/ConsoleApp18.dll
and all other dll and exe files...

2023-10-30 20:04 UTC, andrii-s-spitzer-lpnu-ua approved these changes

2023-10-30 21:44 UTC, merged